// <auto-generated />
using System;
using CesiumApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CesiumApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722022916_AddEarthquakeRecords")]
    partial class AddEarthquakeRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CesiumApi.Models.AnnualLeaveRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CarriedOverDays")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RemainingDays")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalDays")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UsedDays")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AnnualLeaveRecords");
                });

            modelBuilder.Entity("CesiumApi.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("CheckInTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("CheckOutTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("CesiumApi.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Leader")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "北京市朝阳区建国路88号",
                            Code = "HQ",
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3103),
                            Email = "zhangzong@company.com",
                            IsActive = true,
                            Leader = "张总",
                            Name = "总公司",
                            Phone = "010-88888888",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "北京市朝阳区建国路88号A座3层",
                            Code = "TECH",
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3109),
                            Email = "tech@company.com",
                            IsActive = true,
                            Leader = "李经理",
                            Name = "技术部",
                            ParentId = 1,
                            Phone = "010-88888801",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "北京市朝阳区建国路88号A座5层",
                            Code = "PROD",
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3110),
                            Email = "product@company.com",
                            IsActive = true,
                            Leader = "王经理",
                            Name = "产品部",
                            ParentId = 1,
                            Phone = "010-88888802",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 4,
                            Address = "北京市朝阳区建国路88号B座2层",
                            Code = "MKT",
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3112),
                            Email = "marketing@company.com",
                            IsActive = true,
                            Leader = "赵经理",
                            Name = "市场部",
                            ParentId = 1,
                            Phone = "010-88888803",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 5,
                            Address = "北京市朝阳区建国路88号B座3层",
                            Code = "SALES",
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3113),
                            Email = "sales@company.com",
                            IsActive = true,
                            Leader = "孙经理",
                            Name = "销售部",
                            ParentId = 1,
                            Phone = "010-88888804",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 6,
                            Address = "北京市朝阳区建国路88号A座8层",
                            Code = "HR",
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3149),
                            Email = "hr@company.com",
                            IsActive = true,
                            Leader = "周经理",
                            Name = "人事部",
                            ParentId = 1,
                            Phone = "010-88888805",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 7,
                            Address = "北京市朝阳区建国路88号A座9层",
                            Code = "FIN",
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3151),
                            Email = "finance@company.com",
                            IsActive = true,
                            Leader = "吴经理",
                            Name = "财务部",
                            ParentId = 1,
                            Phone = "010-88888806",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 8,
                            Address = "北京市朝阳区建国路88号A座301室",
                            Code = "DEV1",
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3152),
                            Email = "dev1@company.com",
                            IsActive = true,
                            Leader = "郑组长",
                            Name = "研发一组",
                            ParentId = 2,
                            Phone = "010-88888011",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 9,
                            Address = "北京市朝阳区建国路88号A座302室",
                            Code = "DEV2",
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3153),
                            Email = "dev2@company.com",
                            IsActive = true,
                            Leader = "陈组长",
                            Name = "研发二组",
                            ParentId = 2,
                            Phone = "010-88888012",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 10,
                            Address = "北京市朝阳区建国路88号A座4层",
                            Code = "OPS",
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3154),
                            Email = "ops@company.com",
                            IsActive = true,
                            Leader = "刘组长",
                            Name = "运维部",
                            ParentId = 2,
                            Phone = "010-88888013",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("CesiumApi.Models.EarthquakeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Depth")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double>("Lng")
                        .HasColumnType("REAL");

                    b.Property<double>("Magnitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Magnitude");

                    b.HasIndex("Region");

                    b.HasIndex("Time");

                    b.ToTable("EarthquakeRecords");
                });

            modelBuilder.Entity("CesiumApi.Models.LeaveRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApproverId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Days")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Hours")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("UserId");

                    b.ToTable("LeaveRecords");
                });

            modelBuilder.Entity("CesiumApi.Models.LoginLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrowserInfo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsInfo")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoginTime");

                    b.HasIndex("UserId");

                    b.ToTable("LoginLogs");
                });

            modelBuilder.Entity("CesiumApi.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("Permission")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(2949),
                            Icon = "Home",
                            IsVisible = true,
                            Name = "首页",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(2955),
                            Icon = "Dashboard",
                            IsVisible = true,
                            Name = "工作台",
                            ParentId = 1,
                            Path = "/workbench",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(2957),
                            Icon = "Analytics",
                            IsVisible = true,
                            Name = "数据分析",
                            ParentId = 1,
                            Path = "/analysis",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(2958),
                            Icon = "Notifications",
                            IsVisible = true,
                            Name = "通知中心",
                            ParentId = 1,
                            Path = "/notifications",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(2959),
                            Icon = "Send",
                            IsVisible = true,
                            Name = "发送消息",
                            ParentId = 1,
                            Path = "/send-notification",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(2961),
                            Icon = "Dashboard",
                            IsVisible = true,
                            Name = "仪表盘",
                            Path = "/dashboard",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(2962),
                            Icon = "DesktopWindows",
                            IsVisible = true,
                            Name = "大屏展示",
                            Path = "/big-screen",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(2963),
                            Icon = "Map",
                            IsVisible = true,
                            Name = "地图相关",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(2964),
                            Icon = "Map",
                            IsVisible = true,
                            Name = "Cesium地图",
                            ParentId = 8,
                            Path = "/map",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(2966),
                            Icon = "Layers",
                            IsVisible = true,
                            Name = "OpenLayer地图",
                            ParentId = 8,
                            Path = "/openlayer-map",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(2967),
                            Icon = "MapOutlined",
                            IsVisible = true,
                            Name = "Leaflet地图",
                            ParentId = 8,
                            Path = "/leaflet-map",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(2969),
                            Icon = "TableChart",
                            IsVisible = true,
                            Name = "数据表格",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(2970),
                            Icon = "Volcano",
                            IsVisible = true,
                            Name = "地震数据",
                            ParentId = 12,
                            Path = "/earthquake-table",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(2971),
                            Icon = "Storm",
                            IsVisible = true,
                            Name = "台风数据",
                            ParentId = 12,
                            Path = "/typhoon-table",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(2972),
                            Icon = "Waves",
                            IsVisible = true,
                            Name = "风力数据",
                            ParentId = 12,
                            Path = "/wind-table",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3031),
                            Icon = "Air",
                            IsVisible = true,
                            Name = "空气质量",
                            ParentId = 12,
                            Path = "/airquality-table",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3035),
                            Icon = "Settings",
                            IsVisible = true,
                            Name = "权限管理",
                            Permission = "admin",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3036),
                            Icon = "People",
                            IsVisible = true,
                            Name = "用户管理",
                            ParentId = 17,
                            Path = "/user-management",
                            Permission = "admin",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3037),
                            Icon = "Shield",
                            IsVisible = true,
                            Name = "角色管理",
                            ParentId = 17,
                            Path = "/role-management",
                            Permission = "admin",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3038),
                            Icon = "Menu",
                            IsVisible = true,
                            Name = "菜单管理",
                            ParentId = 17,
                            Path = "/menu-management",
                            Permission = "admin",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3039),
                            Icon = "Business",
                            IsVisible = true,
                            Name = "部门管理",
                            ParentId = 17,
                            Path = "/department-management",
                            Permission = "admin",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3041),
                            Icon = "Schedule",
                            IsVisible = true,
                            Name = "考勤管理",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3042),
                            Icon = "Description",
                            IsVisible = true,
                            Name = "打卡报表",
                            ParentId = 22,
                            Path = "/attendance-report",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3043),
                            Icon = "Timer",
                            IsVisible = true,
                            Name = "工时报表",
                            ParentId = 22,
                            Path = "/workhour-report",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3044),
                            Icon = "HolidayVillage",
                            IsVisible = true,
                            Name = "休假报表",
                            ParentId = 22,
                            Path = "/leave-report",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3045),
                            Icon = "BeachAccess",
                            IsVisible = true,
                            Name = "年假报表",
                            ParentId = 22,
                            Path = "/annual-leave-report",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3046),
                            Icon = "History",
                            IsVisible = true,
                            Name = "日志管理",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3047),
                            Icon = "History",
                            IsVisible = true,
                            Name = "登录日志",
                            ParentId = 27,
                            Path = "/login-log-report",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3049),
                            Icon = "FindInPage",
                            IsVisible = true,
                            Name = "审计日志",
                            ParentId = 27,
                            Path = "/audit-log-report",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3050),
                            Icon = "Visibility",
                            IsVisible = true,
                            Name = "访客日志",
                            ParentId = 27,
                            Path = "/visitor-log-report",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3051),
                            Icon = "Insights",
                            IsVisible = true,
                            Name = "影像转BIM",
                            Path = "/image-to-bim",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3052),
                            Icon = "Settings",
                            IsVisible = true,
                            Name = "其他",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3053),
                            Icon = "Info",
                            IsVisible = true,
                            Name = "简介",
                            ParentId = 32,
                            Path = "/settings/introduction",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3054),
                            Icon = "Help",
                            IsVisible = true,
                            Name = "常见问题",
                            ParentId = 32,
                            Path = "/settings/faq",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3055),
                            Icon = "Send",
                            IsVisible = true,
                            Name = "聊天",
                            ParentId = 32,
                            Path = "/settings/chat",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3057),
                            Icon = "Storage",
                            IsVisible = true,
                            Name = "文件管理",
                            ParentId = 32,
                            Path = "/settings/files",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3058),
                            Icon = "Settings",
                            IsVisible = true,
                            Name = "设置",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3059),
                            Icon = "Info",
                            IsVisible = true,
                            Name = "简介",
                            ParentId = 37,
                            Path = "/settings/introduction",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3060),
                            Icon = "Settings",
                            IsVisible = true,
                            Name = "设置",
                            ParentId = 37,
                            Path = "/settings",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3062),
                            Icon = "Wallpaper",
                            IsVisible = true,
                            Name = "背景设置",
                            ParentId = 37,
                            Path = "/settings/background",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3063),
                            Icon = "DashboardOutlined",
                            IsVisible = true,
                            Name = "看板",
                            ParentId = 37,
                            Path = "/settings/dashboard",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3065),
                            Icon = "Folder",
                            IsVisible = true,
                            Name = "项目",
                            ParentId = 37,
                            Path = "/settings/projects",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3066),
                            Icon = "Help",
                            IsVisible = true,
                            Name = "常见问题",
                            ParentId = 37,
                            Path = "/settings/faq",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3067),
                            Icon = "People",
                            IsVisible = true,
                            Name = "个人资料",
                            ParentId = 37,
                            Path = "/settings/users",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3068),
                            Icon = "Security",
                            IsVisible = true,
                            Name = "认证",
                            ParentId = 37,
                            Path = "/settings/auth",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3069),
                            Icon = "Storage",
                            IsVisible = true,
                            Name = "文件管理",
                            ParentId = 37,
                            Path = "/settings/files",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2026, 7, 22, 2, 29, 15, 762, DateTimeKind.Utc).AddTicks(3070),
                            Icon = "Send",
                            IsVisible = true,
                            Name = "聊天",
                            ParentId = 37,
                            Path = "/settings/chat",
                            SortOrder = 10
                        });
                });

            modelBuilder.Entity("CesiumApi.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Read")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("Read");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("CesiumApi.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "拥有所有权限",
                            Name = "超级管理员"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "拥有大部分管理权限",
                            Name = "管理员"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "普通用户权限",
                            Name = "普通用户"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "只读权限",
                            Name = "访客"
                        });
                });

            modelBuilder.Entity("CesiumApi.Models.RoleMenu", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("RoleMenus");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            MenuId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 11
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 12
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 13
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 14
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 15
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 16
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 17
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 18
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 19
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 20
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 21
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 22
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 23
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 24
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 25
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 26
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 27
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 28
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 29
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 30
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 31
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 32
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 33
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 34
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 35
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 36
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 37
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 38
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 39
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 40
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 41
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 42
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 43
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 44
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 45
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 46
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 47
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 2
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 6
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 7
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 8
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 9
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 10
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 12
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 13
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 14
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 17
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 18
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 19
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 22
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 23
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 24
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 27
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 28
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 29
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 2
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 3
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 4
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 6
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 7
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 8
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 9
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 12
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 13
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 14
                        },
                        new
                        {
                            RoleId = 4,
                            MenuId = 1
                        },
                        new
                        {
                            RoleId = 4,
                            MenuId = 2
                        },
                        new
                        {
                            RoleId = 4,
                            MenuId = 6
                        },
                        new
                        {
                            RoleId = 4,
                            MenuId = 7
                        });
                });

            modelBuilder.Entity("CesiumApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CesiumApi.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("CesiumApi.Models.VisitorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("PageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Referrer")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VisitTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress");

                    b.HasIndex("VisitTime");

                    b.ToTable("VisitorLogs");
                });

            modelBuilder.Entity("CesiumApi.Models.WorkHourRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HolidayHours")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OvertimeHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RegularHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WeekendHours")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkHourRecords");
                });

            modelBuilder.Entity("CesiumApi.Models.AnnualLeaveRecord", b =>
                {
                    b.HasOne("CesiumApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CesiumApi.Models.AttendanceRecord", b =>
                {
                    b.HasOne("CesiumApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CesiumApi.Models.Department", b =>
                {
                    b.HasOne("CesiumApi.Models.Department", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CesiumApi.Models.LeaveRecord", b =>
                {
                    b.HasOne("CesiumApi.Models.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId");

                    b.HasOne("CesiumApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CesiumApi.Models.LoginLog", b =>
                {
                    b.HasOne("CesiumApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CesiumApi.Models.Menu", b =>
                {
                    b.HasOne("CesiumApi.Models.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CesiumApi.Models.RoleMenu", b =>
                {
                    b.HasOne("CesiumApi.Models.Menu", "Menu")
                        .WithMany("RoleMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CesiumApi.Models.Role", "Role")
                        .WithMany("RoleMenus")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CesiumApi.Models.User", b =>
                {
                    b.HasOne("CesiumApi.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CesiumApi.Models.UserRole", b =>
                {
                    b.HasOne("CesiumApi.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CesiumApi.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CesiumApi.Models.WorkHourRecord", b =>
                {
                    b.HasOne("CesiumApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CesiumApi.Models.Department", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CesiumApi.Models.Menu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RoleMenus");
                });

            modelBuilder.Entity("CesiumApi.Models.Role", b =>
                {
                    b.Navigation("RoleMenus");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CesiumApi.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
