// <auto-generated />
using System;
using CesiumApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CesiumApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707143506_UpdateMenus")]
    partial class UpdateMenus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CesiumApi.Models.AnnualLeaveRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CarriedOverDays")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RemainingDays")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalDays")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UsedDays")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AnnualLeaveRecords");
                });

            modelBuilder.Entity("CesiumApi.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("CheckInTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("CheckOutTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("CesiumApi.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Leader")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "北京市朝阳区建国路88号",
                            Code = "HQ",
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(5044),
                            Email = "zhangzong@company.com",
                            IsActive = true,
                            Leader = "张总",
                            Name = "总公司",
                            Phone = "010-88888888",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "北京市朝阳区建国路88号A座3层",
                            Code = "TECH",
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(5050),
                            Email = "tech@company.com",
                            IsActive = true,
                            Leader = "李经理",
                            Name = "技术部",
                            ParentId = 1,
                            Phone = "010-88888801",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "北京市朝阳区建国路88号A座5层",
                            Code = "PROD",
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(5052),
                            Email = "product@company.com",
                            IsActive = true,
                            Leader = "王经理",
                            Name = "产品部",
                            ParentId = 1,
                            Phone = "010-88888802",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 4,
                            Address = "北京市朝阳区建国路88号B座2层",
                            Code = "MKT",
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(5054),
                            Email = "marketing@company.com",
                            IsActive = true,
                            Leader = "赵经理",
                            Name = "市场部",
                            ParentId = 1,
                            Phone = "010-88888803",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 5,
                            Address = "北京市朝阳区建国路88号B座3层",
                            Code = "SALES",
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(5057),
                            Email = "sales@company.com",
                            IsActive = true,
                            Leader = "孙经理",
                            Name = "销售部",
                            ParentId = 1,
                            Phone = "010-88888804",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 6,
                            Address = "北京市朝阳区建国路88号A座8层",
                            Code = "HR",
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(5059),
                            Email = "hr@company.com",
                            IsActive = true,
                            Leader = "周经理",
                            Name = "人事部",
                            ParentId = 1,
                            Phone = "010-88888805",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 7,
                            Address = "北京市朝阳区建国路88号A座9层",
                            Code = "FIN",
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(5061),
                            Email = "finance@company.com",
                            IsActive = true,
                            Leader = "吴经理",
                            Name = "财务部",
                            ParentId = 1,
                            Phone = "010-88888806",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 8,
                            Address = "北京市朝阳区建国路88号A座301室",
                            Code = "DEV1",
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(5063),
                            Email = "dev1@company.com",
                            IsActive = true,
                            Leader = "郑组长",
                            Name = "研发一组",
                            ParentId = 2,
                            Phone = "010-88888011",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 9,
                            Address = "北京市朝阳区建国路88号A座302室",
                            Code = "DEV2",
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(5065),
                            Email = "dev2@company.com",
                            IsActive = true,
                            Leader = "陈组长",
                            Name = "研发二组",
                            ParentId = 2,
                            Phone = "010-88888012",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 10,
                            Address = "北京市朝阳区建国路88号A座4层",
                            Code = "OPS",
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(5067),
                            Email = "ops@company.com",
                            IsActive = true,
                            Leader = "刘组长",
                            Name = "运维部",
                            ParentId = 2,
                            Phone = "010-88888013",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("CesiumApi.Models.LeaveRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ApproverId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Days")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Hours")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("UserId");

                    b.ToTable("LeaveRecords");
                });

            modelBuilder.Entity("CesiumApi.Models.LoginLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrowserInfo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsInfo")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoginTime");

                    b.HasIndex("UserId");

                    b.ToTable("LoginLogs");
                });

            modelBuilder.Entity("CesiumApi.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<string>("Permission")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4863),
                            Icon = "Home",
                            IsVisible = true,
                            Name = "首页",
                            Permission = "home",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4869),
                            Icon = "Dashboard",
                            IsVisible = true,
                            Name = "工作台",
                            ParentId = 1,
                            Path = "/workbench",
                            Permission = "home:workbench",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4871),
                            Icon = "Analytics",
                            IsVisible = true,
                            Name = "分析页",
                            ParentId = 1,
                            Path = "/analysis",
                            Permission = "home:analysis",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4873),
                            Icon = "Notifications",
                            IsVisible = true,
                            Name = "通知中心",
                            ParentId = 1,
                            Path = "/notifications",
                            Permission = "home:notifications",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4875),
                            Icon = "Send",
                            IsVisible = true,
                            Name = "发送消息",
                            ParentId = 1,
                            Path = "/send-notification",
                            Permission = "home:sendNotification",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4877),
                            Icon = "Map",
                            IsVisible = true,
                            Name = "地图管理",
                            Permission = "map",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4879),
                            Icon = "Map",
                            IsVisible = true,
                            Name = "Cesium地图",
                            ParentId = 6,
                            Path = "/map",
                            Permission = "map:cesium",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4880),
                            Icon = "Layers",
                            IsVisible = true,
                            Name = "OL地图",
                            ParentId = 6,
                            Path = "/openlayer-map",
                            Permission = "map:openlayer",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4882),
                            Icon = "MapOutlined",
                            IsVisible = true,
                            Name = "Leaflet地图",
                            ParentId = 6,
                            Path = "/leaflet-map",
                            Permission = "map:leaflet",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4884),
                            Icon = "BarChart",
                            IsVisible = true,
                            Name = "专题数据",
                            Permission = "data",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4885),
                            Icon = "Volcano",
                            IsVisible = true,
                            Name = "地震数据表格",
                            ParentId = 10,
                            Path = "/earthquake-table",
                            Permission = "data:earthquake",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4887),
                            Icon = "Storm",
                            IsVisible = true,
                            Name = "台风数据表格",
                            ParentId = 10,
                            Path = "/typhoon-table",
                            Permission = "data:typhoon",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4889),
                            Icon = "Waves",
                            IsVisible = true,
                            Name = "风向数据表格",
                            ParentId = 10,
                            Path = "/wind-table",
                            Permission = "data:wind",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4890),
                            Icon = "Air",
                            IsVisible = true,
                            Name = "空气质量数据表格",
                            ParentId = 10,
                            Path = "/airquality-table",
                            Permission = "data:airquality",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4892),
                            Icon = "Monitor",
                            IsVisible = true,
                            Name = "大屏",
                            Path = "/big-screen",
                            Permission = "bigScreen",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4893),
                            Icon = "Table",
                            IsVisible = true,
                            Name = "数据表格",
                            Path = "/dataTables",
                            Permission = "dataTables",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4895),
                            Icon = "Settings",
                            IsVisible = true,
                            Name = "权限管理",
                            Permission = "permission",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4896),
                            Icon = "People",
                            IsVisible = true,
                            Name = "用户管理",
                            ParentId = 17,
                            Path = "/user-management",
                            Permission = "permission:users",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4898),
                            Icon = "Shield",
                            IsVisible = true,
                            Name = "角色管理",
                            ParentId = 17,
                            Path = "/role-management",
                            Permission = "permission:roles",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4901),
                            Icon = "Menu",
                            IsVisible = true,
                            Name = "菜单管理",
                            ParentId = 17,
                            Path = "/menu-management",
                            Permission = "permission:menus",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4902),
                            Icon = "Business",
                            IsVisible = true,
                            Name = "部门管理",
                            ParentId = 17,
                            Path = "/department-management",
                            Permission = "permission:departments",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4904),
                            Icon = "Schedule",
                            IsVisible = true,
                            Name = "考勤管理",
                            Permission = "attendance",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4960),
                            Icon = "Description",
                            IsVisible = true,
                            Name = "打卡报表",
                            ParentId = 22,
                            Path = "/attendance-report",
                            Permission = "attendance:report",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4962),
                            Icon = "Timer",
                            IsVisible = true,
                            Name = "工时报表",
                            ParentId = 22,
                            Path = "/workhour-report",
                            Permission = "attendance:workhour",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4963),
                            Icon = "HolidayVillage",
                            IsVisible = true,
                            Name = "休假报表",
                            ParentId = 22,
                            Path = "/leave-report",
                            Permission = "attendance:leave",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4965),
                            Icon = "BeachAccess",
                            IsVisible = true,
                            Name = "年假报表",
                            ParentId = 22,
                            Path = "/annual-leave-report",
                            Permission = "attendance:annual",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4966),
                            Icon = "History",
                            IsVisible = true,
                            Name = "日志管理",
                            Permission = "log",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4968),
                            Icon = "History",
                            IsVisible = true,
                            Name = "登录日志",
                            ParentId = 27,
                            Path = "/login-log-report",
                            Permission = "log:login",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4969),
                            Icon = "FindInPage",
                            IsVisible = true,
                            Name = "查询日志",
                            ParentId = 27,
                            Path = "/audit-log-report",
                            Permission = "log:audit",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4971),
                            Icon = "Visibility",
                            IsVisible = true,
                            Name = "访客日志",
                            ParentId = 27,
                            Path = "/visitor-log-report",
                            Permission = "log:visitor",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4973),
                            Icon = "Image",
                            IsVisible = true,
                            Name = "图片转BIM",
                            Path = "/image-to-bim",
                            Permission = "imageToBim",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4974),
                            Icon = "Settings",
                            IsVisible = true,
                            Name = "设置",
                            Permission = "settings",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4976),
                            Icon = "Info",
                            IsVisible = true,
                            Name = "简介",
                            ParentId = 32,
                            Path = "/settings/introduction",
                            Permission = "settings:intro",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4979),
                            Icon = "Settings",
                            IsVisible = true,
                            Name = "设置",
                            ParentId = 32,
                            Path = "/settings",
                            Permission = "settings:main",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4980),
                            Icon = "Wallpaper",
                            IsVisible = true,
                            Name = "背景设置",
                            ParentId = 32,
                            Path = "/settings/background",
                            Permission = "settings:background",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4982),
                            Icon = "DashboardOutlined",
                            IsVisible = true,
                            Name = "看板",
                            ParentId = 32,
                            Path = "/settings/dashboard",
                            Permission = "settings:dashboard",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4985),
                            Icon = "Folder",
                            IsVisible = true,
                            Name = "项目",
                            ParentId = 32,
                            Path = "/settings/projects",
                            Permission = "settings:projects",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4987),
                            Icon = "Help",
                            IsVisible = true,
                            Name = "常见问题",
                            ParentId = 32,
                            Path = "/settings/faq",
                            Permission = "settings:faq",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4989),
                            Icon = "People",
                            IsVisible = true,
                            Name = "用户",
                            ParentId = 32,
                            Path = "/settings/users",
                            Permission = "settings:users",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4990),
                            Icon = "Security",
                            IsVisible = true,
                            Name = "认证",
                            ParentId = 32,
                            Path = "/settings/auth",
                            Permission = "settings:auth",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4992),
                            Icon = "Storage",
                            IsVisible = true,
                            Name = "文件管理",
                            ParentId = 32,
                            Path = "/settings/files",
                            Permission = "settings:files",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4993),
                            Icon = "Send",
                            IsVisible = true,
                            Name = "聊天",
                            ParentId = 32,
                            Path = "/settings/chat",
                            Permission = "settings:chat",
                            SortOrder = 10
                        });
                });

            modelBuilder.Entity("CesiumApi.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Read")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("Read");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("CesiumApi.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4712),
                            Description = "系统管理员",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 7, 14, 35, 5, 835, DateTimeKind.Utc).AddTicks(4719),
                            Description = "普通用户",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("CesiumApi.Models.RoleMenu", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("RoleMenus");
                });

            modelBuilder.Entity("CesiumApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CesiumApi.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("CesiumApi.Models.VisitorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("PageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Referrer")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VisitTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress");

                    b.HasIndex("VisitTime");

                    b.ToTable("VisitorLogs");
                });

            modelBuilder.Entity("CesiumApi.Models.WorkHourRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HolidayHours")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OvertimeHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RegularHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WeekendHours")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkHourRecords");
                });

            modelBuilder.Entity("CesiumApi.Models.AnnualLeaveRecord", b =>
                {
                    b.HasOne("CesiumApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CesiumApi.Models.AttendanceRecord", b =>
                {
                    b.HasOne("CesiumApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CesiumApi.Models.Department", b =>
                {
                    b.HasOne("CesiumApi.Models.Department", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CesiumApi.Models.LeaveRecord", b =>
                {
                    b.HasOne("CesiumApi.Models.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId");

                    b.HasOne("CesiumApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CesiumApi.Models.LoginLog", b =>
                {
                    b.HasOne("CesiumApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CesiumApi.Models.Menu", b =>
                {
                    b.HasOne("CesiumApi.Models.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CesiumApi.Models.RoleMenu", b =>
                {
                    b.HasOne("CesiumApi.Models.Menu", "Menu")
                        .WithMany("RoleMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CesiumApi.Models.Role", "Role")
                        .WithMany("RoleMenus")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CesiumApi.Models.User", b =>
                {
                    b.HasOne("CesiumApi.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CesiumApi.Models.UserRole", b =>
                {
                    b.HasOne("CesiumApi.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CesiumApi.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CesiumApi.Models.WorkHourRecord", b =>
                {
                    b.HasOne("CesiumApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CesiumApi.Models.Department", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CesiumApi.Models.Menu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RoleMenus");
                });

            modelBuilder.Entity("CesiumApi.Models.Role", b =>
                {
                    b.Navigation("RoleMenus");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CesiumApi.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
